version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - ASGI_THREADS=10

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data:
  node_modules:
  redis_data:  # Ensure Redis volume if needed
